### ISSUE TITLE
Entry point scripts don't get byte-compiled

### ISSUE THREAD

**Issue by rossburton** [pypa/installer#112]
Should entrypoint scripts get byte compiled?  Currently if I install eg wheel, it byte-compiles the module but not the `wheel` entrypoint in bindir.

**Comment by eli-schwartz** [comment]
I very much doubt it. Neither pip not setup.py install ever did so, and since they are run as files the only way to byte-compile them would be to replace them rather than add them as a side cache. It would therefore become impossible to conveniently read or understand what one does, or rebuild it.

And there's no real benefit. An entry point script is by design extremely short (3 imports, 3 lines of logic -- and could sacrifice windows portability in exchange for being one import and one line of logic) and merely obtains a main() style function from a module which is byte compiled.

**Comment by rossburton** [comment]
Our current tooling does `compile_all` and ends up creating `/usr/bin/__pycache__/foo.pyc`, are you saying they're never actually used?

**Comment by pradyunsg** [comment]
I see that @eli-schwartz got around to responding to this before I could! :)

As noted, not compiling these is the right thing to do.
