### ISSUE TITLE
Support checking install dependencies

### ISSUE THREAD

**Issue by nanonyme** [pypa/installer#196]
Currently pypa/build supports checking build dependencies (and this is done by default). But when package is installed with pypa/installer, its runtime dependencies do not get validated. It would be nice that there would be an option for this at least.

**Comment by nanonyme** [comment]
Looks like the relevant runtime dependency information is available through output of parse_metadata_file. However, processing this might be tricky without packaging which installer cannot really depend on due to cycles.

**Comment by nanonyme** [comment]
Essentially why packaging makes things simpler here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/15404/diffs#d1ff495ddd14f96492c7b23fd7809ddbf1933ede ; this is extracted from importlib.metadata but I guess same data would be present through METADATA file.

**Comment by pradyunsg** [comment]
This is functionally covered by https://pypa-build.readthedocs.io/en/stable/api.html#build.check_dependency which can be invoked by the caller... I don't see much value in duplicating that functionality here TBH.

**Comment by nanonyme** [comment]
@pradyunsg you are misreading. I said that covers build dependencies. There is nothing that validates runtime dependencies.

**Comment by nanonyme** [comment]
Currently only pip is capable of stating that package runtime dependencies are fulfilled

**Comment by nanonyme** [comment]
Why I mentioned it here is runtime dependency validation makes sense when something is installed while build dependencies make sense to be validated when something is built. I don't really mind what grows this support.

**Comment by eli-schwartz** [comment]
> This is functionally covered by https://pypa-build.readthedocs.io/en/stable/api.html#build.check_dependency which can be invoked by the caller... I don't see much value in duplicating that functionality here TBH.

That does indeed functionally cover the existence of library methods that take a list of dependency specifiers and check whether they are installed. It would be a valid library to reach for as a dependency for the `python -m installer foo-1.0-*.whl` CLI to use in implementing the desired feature request...

... which wasn't at all about building out the ecosystem of library APIs as far as I can tell. :)

**Comment by eli-schwartz** [comment]
That being said I do think that it's not particularly urgent to have. The people who are interested in the `installer` CLI and are concerned with bootstrap dependencies are also the people least likely to need it. In fact, I would typically pass  `--skip-dependency-check` to the `python -m build` command too.

**Comment by nanonyme** [comment]
We are using that check but it does something different than what I requested. Normally packages do not declare their runtime dependencies as required for building wheel which is correct. I am after a check that says once wheel is installed, all its dependencies are fulfilled.

**Comment by eli-schwartz** [comment]
What I mean is that I would ignore both checks for similar reasons. You don't really need to check it since you can almost certainly just generate this part of a flatpak manifest programmatically, without baking it into the build/install pipeline.

And often when you install a wheel (in particular, if you are using `--destdir`), you haven't yet installed its dependencies, but will do so later after merging the destdir into a live filesystem. So you cannot really validate the install-time dependencies like this.

**Comment by nanonyme** [comment]
Actually commonly with flatpak pip is used to generate incomplete recipes and then pip is used to validate runtime dependencies. But I am not using a stack that uses pip. I am using stack that uses build+installer and that stack cannot validate runtime dependencies.

**Comment by nanonyme** [comment]
There is no such application or package for us. We use pypa/build to build wheels of a package from command line distro recipe, then pypa/installer to install *without pip* because of system bootstrappability requirements. There request was made here because for symmetry pypa/build handles build dependencies whereas I expected pypa/installer to handle runtime dependencies. Clearly that has to then be implemented in another project that is not pip and can be PEP517 bootstrapped if it's not desired here.

**Comment by eli-schwartz** [comment]
A resolver would be something that takes candidate packages/versions from PyPI and calculates which set of dependencies is a valid install plan. It has to *resolve* versions, particularly.

That wasn't what was asked for here anyway -- what was asked for here was a *validator*. A validator only cares about one set of dependencies -- the one that is already installed -- and simply asks the yes-or-no question "am I valid right now". This is entirely straightforward -- iterate over a one-dimensional list, check whether each element is currently installed. You don't need much of anything in order to do this, other than, well, `packaging.version.Version` to do PEP-compatible validation of the version part of a Requires-Dist, as mentioned in the second comment.

It cannot be done without at least one non-stdlib dependency, which opposes one of the goals of `installer` -- that the CLI frontend `python -m installer` can be used by people who want to install wheel files in a bootstrap scenario, before any other packages have been installed, which means no installed copy of `packaging`.

But it's not about "resolvers", it's about parsing versions in a PEP-compliant manner.
